typo
Signed-off-by: Michal Minář <miminar@redhat.com>

diff --git a/insecure-registry-for-vflow-template.yaml b/insecure-registry-for-vflow-template.yaml
--- a/insecure-registry-for-vflow-template.yaml
+++ b/insecure-registry-for-vflow-template.yaml
@@ -153,7 +153,7 @@ objects:
             client_version="$(sed -n 's/^\([cC]lient.*:\|oc\) v\([0-9]\+\.[0-9]\+\).*/\2/p' \
                               <<<"$version" | head -n 1)"
             if [[ -z "${client_version:-}" ]]; then
-              printf 'WARNING: Failed to determin oc client version!\n' >&2
+              printf 'WARNING: Failed to determine oc client version!\n' >&2
             elif [[ "${server_version}" != "${client_version}" ]]; then
               printf 'WARNING: Client version != Server version (%s != %s).\n' "$client_version" "$server_version" >&2
               printf '         Please reinstantiate this template with the correct BASE_IMAGE_TAG parameter (e.g. v%s)."\n' >&2 \
